name: Notify Slack on Branch Events

on:
  create:
    branches:
      - '**'
  delete:
    branches:
      - '**'

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Notify Slack
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: workflow,job,commit,repo,ref,author,took
        custom_payload: |
          {
            "attachments": [{
              "color": "${{ job.status }}",
              "fields": [{
                "title": "Repository",
                "value": "${{ github.repository }}",
                "short": true
              }, {
                "title": "Ref",
                "value": "${{ github.ref }}",
                "short": true
              }]
            }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        GITHUB_TOKEN: ${{ github.token }}
